#!/bin/bash
# 该脚本根据 md5 哈希查找指定目录中的重复文件

DIR=${1:-.}
declare -A filehash

while IFS= read -r -d '' file; do
    hash=$(md5sum "$file" | awk '{print $1}')
    if [[ -n "${filehash[$hash]}" ]]; then
        echo "Duplicate found:"
        echo "  ${filehash[$hash]}"
        echo "  $file"
    else
        filehash[$hash]="$file"
    fi
done < <(find "$DIR" -type f -print0)
